# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/"
    groups:
      aws-sdk-go:
        patterns:
          - "github.com/aws/aws-sdk-go-v2/*"
    ignore:
      - dependency-name: "golang.org/x/tools"
      - dependency-name: "google.golang.org/grpc"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/v2/awsv1shim"
    ignore:
      - dependency-name: "github.com/aws/aws-sdk-go-v2"
      - dependency-name: "golang.org/x/tools"
      - dependency-name: "google.golang.org/grpc"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/tools"
    ignore:
      - dependency-name: "golang.org/x/tools"
      - dependency-name: "google.golang.org/grpc"
    schedule:
      interval: "daily"
