dist: xenial
language: go
go:
- "1.12.x"

env:
  GOFLAGS=-mod=vendor

matrix:
  fast_finish: true
  allow_failures:
  - go: tip

install:
- make tools

script:
- make lint
- make test

branches:
  only:
  - master
